name = "YangMills"
defaultTargets = ["YangMills"]

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "v4.15.0"

[[lean_lib]]
name = "YangMills"
globs = ["YangMills.BFSConvergenceFinal",
 "YangMills.ClusterDecomposition",
 "YangMills.EntropicPrinciple_Standalone",
 "YangMills.Gap1.BRSTMeasure",
 "YangMills.SyntaxTest"]
