/-
LatticeGauge/UrsellCoefficients.lean — Phase 3, thirty-seventh stone.

FINITE URSELL COEFFICIENTS FOR HARD-CORE GRAPHS (architecture:
Sol/GPT-5.6, route A3; execution: Fable). This stone builds the finite
combinatorial object that a future cluster series will use — and
DELIBERATELY DOES NOT TOUCH log Z: even in finite volume, the usual
expansion of log Z is an infinite series (a single polymer of weight w
gives log(1+w) = Σ (−1)^{n+1} wⁿ/n), so no "finite identity for
log Z" is claimed. The Ursell coefficient is defined as a FINITE
signed integer sum over connected spanning edge sets of the
incompatibility graph: φ(γ) = Σ_{E ⊆ E_inc, connected} (−1)^{|E|}.
Architecture (architect's decisions): internal canonical edges i < j
(OrderedEdge subtype, never in public polymer statements — the public
graph is SimpleGraph (Fin n)); the index graph imposes i ≠ j, so
distinct occurrences of the SAME polymer may be adjacent while loops
stay forbidden (incompatibility of polymers is NOT irreflexive);
disconnected ⟹ coefficient 0 is proved STRUCTURALLY (the filter is
empty), not by a cancellation trick; the (1−1)^m cancellation is a
SEPARATE tool lemma for future inclusion–exclusion; permutation
symmetry is deferred to stone 38 and NOT claimed here. CONVENTION
(explicit, from Mathlib's Connected): Connected requires Nonempty, so
for n = 0 no edge set passes the filter and the coefficient is 0;
for n = 1 the empty edge set is connected and the coefficient is 1.
NOTHING analytic enters: no cluster series, no sums over n, no 1/n!,
no log realZ, no convergence, no |activities|, no spanning trees, no
Penrose, no tree-graph inequality, no Cayley, no polymer counting, no
Kotecký–Preiss, no thermodynamic limit. NO axioms.
-/
import Mathlib
import LatticeGauge.Basic
import LatticeGauge.PlaquetteActivity
import LatticeGauge.PlaquetteConnectivity
import LatticeGauge.PolymerGeometry
import LatticeGauge.PolymerGas

open scoped Classical

namespace LatticeGauge

/-! ## Canonical edges (internal representation) -/

/-- **1. Canonical ordered edges** i < j on Fin n — internal to this
    file; public polymer statements never mention it. -/
abbrev OrderedEdge (n : ℕ) := { e : Fin n × Fin n // e.1 < e.2 }

/-- The canonical edges available in a graph. -/
noncomputable def availableEdges {n : ℕ} (G : SimpleGraph (Fin n)) :
    Finset (OrderedEdge n) :=
  Finset.univ.filter (fun e => G.Adj e.val.1 e.val.2)

theorem mem_availableEdges {n : ℕ} {G : SimpleGraph (Fin n)}
    {e : OrderedEdge n} :
    e ∈ availableEdges G ↔ G.Adj e.val.1 e.val.2 := by
  unfold availableEdges
  simp

/-- **2. The graph generated by a set of canonical edges.** The vertex
    type stays Fin n, so any such graph is spanning by construction. -/
def graphOfEdges {n : ℕ} (E : Finset (OrderedEdge n)) :
    SimpleGraph (Fin n) where
  Adj i j :=
    (∃ h : i < j, (⟨(i, j), h⟩ : OrderedEdge n) ∈ E) ∨
    (∃ h : j < i, (⟨(j, i), h⟩ : OrderedEdge n) ∈ E)
  symm := by
    intro i j h
    rcases h with ⟨hlt, hm⟩ | ⟨hlt, hm⟩
    · exact Or.inr ⟨hlt, hm⟩
    · exact Or.inl ⟨hlt, hm⟩
  loopless := by
    intro i h
    rcases h with ⟨hlt, _⟩ | ⟨hlt, _⟩ <;> exact absurd hlt (lt_irrefl i)

theorem graphOfEdges_adj {n : ℕ} {E : Finset (OrderedEdge n)}
    {i j : Fin n} :
    (graphOfEdges E).Adj i j ↔
      (∃ h : i < j, (⟨(i, j), h⟩ : OrderedEdge n) ∈ E) ∨
      (∃ h : j < i, (⟨(j, i), h⟩ : OrderedEdge n) ∈ E) :=
  Iff.rfl

theorem graphOfEdges_le {n : ℕ} {G : SimpleGraph (Fin n)}
    {E : Finset (OrderedEdge n)} (hE : E ⊆ availableEdges G) :
    graphOfEdges E ≤ G := by
  intro i j hij
  rcases hij with ⟨hlt, hm⟩ | ⟨hlt, hm⟩
  · exact mem_availableEdges.mp (hE hm)
  · exact (mem_availableEdges.mp (hE hm)).symm

private theorem graphOfEdges_empty_no_adj {n : ℕ} :
    ∀ a b : Fin n,
      ¬ (graphOfEdges (∅ : Finset (OrderedEdge n))).Adj a b := by
  intro a b hab
  rcases hab with ⟨_, hm⟩ | ⟨_, hm⟩ <;>
    exact absurd hm (Finset.not_mem_empty _)

/-- If a graph has no edges at all, reachability collapses to
    equality. -/
private theorem reachable_eq_of_no_adj {V : Type*} {G : SimpleGraph V}
    (h : ∀ a b : V, ¬ G.Adj a b) :
    ∀ {u v : V}, G.Reachable u v → u = v := by
  intro u v hr
  obtain ⟨W⟩ := hr
  induction W with
  | nil => rfl
  | cons hadj _ _ => exact absurd hadj (h _ _)

/-! ## Connected spanning edge sets and the coefficient -/

/-- **3. The connected spanning edge sets** of G: subsets of the
    available canonical edges whose generated graph on ALL of Fin n is
    connected (Mathlib convention: Connected requires Nonempty, so
    this is empty for n = 0). -/
noncomputable def connectedSpanningEdgeSets {n : ℕ}
    (G : SimpleGraph (Fin n)) : Finset (Finset (OrderedEdge n)) :=
  (availableEdges G).powerset.filter
    (fun E => (graphOfEdges E).Connected)

theorem mem_connectedSpanningEdgeSets {n : ℕ}
    {G : SimpleGraph (Fin n)} {E : Finset (OrderedEdge n)} :
    E ∈ connectedSpanningEdgeSets G
      ↔ E ⊆ availableEdges G ∧ (graphOfEdges E).Connected := by
  unfold connectedSpanningEdgeSets
  simp [Finset.mem_filter, Finset.mem_powerset]

/-- **4. The graphic Ursell coefficient**: a FINITE, purely
    combinatorial signed integer sum over connected spanning edge
    sets. No polymer weights, no cluster series, no claim about log Z
    or convergence. -/
noncomputable def graphUrsellCoeff {n : ℕ}
    (G : SimpleGraph (Fin n)) : ℤ :=
  ∑ E ∈ connectedSpanningEdgeSets G, (-1 : ℤ) ^ E.card

/-- **C. Disconnected base graph ⟹ coefficient 0** — proved
    STRUCTURALLY: no edge set passes the filter (a connected generated
    subgraph would force the base graph connected by monotonicity), so
    the sum is empty. No (1−1)^m cancellation is involved. -/
theorem graphUrsellCoeff_of_not_connected {n : ℕ}
    (G : SimpleGraph (Fin n)) (h : ¬ G.Connected) :
    graphUrsellCoeff G = 0 := by
  unfold graphUrsellCoeff
  have hempty : connectedSpanningEdgeSets G = ∅ := by
    rw [Finset.eq_empty_iff_forall_not_mem]
    intro E hE
    obtain ⟨hsub, hconn⟩ := mem_connectedSpanningEdgeSets.mp hE
    exact h (hconn.mono (graphOfEdges_le hsub))
  rw [hempty, Finset.sum_empty]

/-- **A (graph form). On one vertex the coefficient is 1**: there are
    no canonical edges, the empty edge set is connected (single
    vertex), and the sum is (−1)⁰ = 1. -/
theorem graphUrsellCoeff_fin_one (G : SimpleGraph (Fin 1)) :
    graphUrsellCoeff G = 1 := by
  have hav : availableEdges G = ∅ := by
    rw [Finset.eq_empty_iff_forall_not_mem]
    intro e _
    have h := e.2
    have heq : e.val.1 = e.val.2 := Subsingleton.elim _ _
    rw [heq] at h
    exact lt_irrefl _ h
  have hconn : (graphOfEdges (∅ : Finset (OrderedEdge 1))).Connected := by
    rw [SimpleGraph.connected_iff]
    refine ⟨fun u v => ?_, ⟨0⟩⟩
    have h : u = v := Subsingleton.elim u v
    subst h
    exact ⟨SimpleGraph.Walk.nil⟩
  unfold graphUrsellCoeff connectedSpanningEdgeSets
  rw [hav, Finset.powerset_empty, Finset.filter_singleton,
    if_pos hconn, Finset.sum_singleton]
  simp

private theorem connected_of_adj_fin2 {G : SimpleGraph (Fin 2)}
    (h : G.Adj 0 1) : G.Connected := by
  rw [SimpleGraph.connected_iff]
  refine ⟨fun u v => ?_, ⟨0⟩⟩
  fin_cases u <;> fin_cases v
  · exact ⟨SimpleGraph.Walk.nil⟩
  · exact ⟨SimpleGraph.Walk.cons h SimpleGraph.Walk.nil⟩
  · exact ⟨SimpleGraph.Walk.cons h.symm SimpleGraph.Walk.nil⟩
  · exact ⟨SimpleGraph.Walk.nil⟩

/-! ## The incompatibility graph of a tuple of polymers -/

variable {N : ℕ}

/-- **5. The incompatibility graph of a tuple.** Adjacency imposes
    i ≠ j (index level), so two DISTINCT occurrences of the same
    polymer may be adjacent while loops stay forbidden — polymer
    incompatibility itself is not irreflexive. Symmetry comes from the
    symmetry of PlaquetteCompatible. Defined for arbitrary tuples of
    Finsets; IsPlaquettePolymer enters future theorems as a
    hypothesis, never as a dependent argument. -/
def polymerIncompatibilityGraph [NeZero N] {n : ℕ}
    (γ : Fin n → Finset (Site N × Dir × Dir)) :
    SimpleGraph (Fin n) where
  Adj i j := i ≠ j ∧ ¬ PlaquetteCompatible (γ i) (γ j)
  symm := by
    rintro i j ⟨hne, hnc⟩
    exact ⟨hne.symm, fun hc => hnc (plaquetteCompatible_symm hc)⟩
  loopless := by
    rintro i ⟨hne, _⟩
    exact hne rfl

/-- **The Ursell coefficient of a tuple of polymer candidates.** -/
noncomputable def ursellCoeff [NeZero N] {n : ℕ}
    (γ : Fin n → Finset (Site N × Dir × Dir)) : ℤ :=
  graphUrsellCoeff (polymerIncompatibilityGraph γ)

/-- **A. Unit case: a single polymer has coefficient 1.** -/
theorem ursellCoeff_single [NeZero N]
    (γ : Fin 1 → Finset (Site N × Dir × Dir)) :
    ursellCoeff γ = 1 :=
  graphUrsellCoeff_fin_one _

/-- **D. Disconnected incompatibility graph ⟹ coefficient 0.** -/
theorem ursellCoeff_of_not_connected [NeZero N] {n : ℕ}
    (γ : Fin n → Finset (Site N × Dir × Dir))
    (h : ¬ (polymerIncompatibilityGraph γ).Connected) :
    ursellCoeff γ = 0 :=
  graphUrsellCoeff_of_not_connected _ h

/-- **E. If n ≥ 2 and all distinct pairs are compatible, the
    coefficient vanishes** (the incompatibility graph has no edges and
    at least two vertices, hence is disconnected). -/
theorem ursellCoeff_of_pairwise_compatible [NeZero N] {n : ℕ}
    (hn : 2 ≤ n) (γ : Fin n → Finset (Site N × Dir × Dir))
    (h : ∀ i j, i ≠ j → PlaquetteCompatible (γ i) (γ j)) :
    ursellCoeff γ = 0 := by
  apply ursellCoeff_of_not_connected
  intro hconn
  have heq := reachable_eq_of_no_adj
    (fun a b hab => hab.2 (h a b hab.1))
    (hconn.preconnected ⟨0, by omega⟩ ⟨1, by omega⟩)
  have hval := congrArg Fin.val heq
  simp at hval

/-- **B. Binary case**: two polymers give 0 if compatible (no edge, two
    vertices, disconnected) and −1 if incompatible (one available
    edge; only the full edge set is connected; sign (−1)¹). -/
theorem ursellCoeff_pair [NeZero N]
    (C D : Finset (Site N × Dir × Dir)) :
    ursellCoeff ![C, D]
      = if PlaquetteCompatible C D then 0 else -1 := by
  by_cases hcomp : PlaquetteCompatible C D
  · rw [if_pos hcomp]
    apply ursellCoeff_of_not_connected
    intro hc
    have hno : ∀ a b : Fin 2,
        ¬ (polymerIncompatibilityGraph ![C, D]).Adj a b := by
      intro a b hab
      obtain ⟨hne, hnc⟩ := hab
      fin_cases a <;> fin_cases b
      · exact hne rfl
      · exact hnc (by simpa using hcomp)
      · exact hnc (by simpa using plaquetteCompatible_symm hcomp)
      · exact hne rfl
    have h01 := reachable_eq_of_no_adj hno (hc.preconnected 0 1)
    exact absurd h01 (by decide)
  · rw [if_neg hcomp]
    have hadj01 : (polymerIncompatibilityGraph ![C, D]).Adj 0 1 :=
      ⟨by decide, by simpa using hcomp⟩
    have hav : availableEdges (polymerIncompatibilityGraph ![C, D])
        = {⟨((0 : Fin 2), (1 : Fin 2)), by decide⟩} := by
      ext e
      rw [mem_availableEdges, Finset.mem_singleton]
      constructor
      · intro _
        have hlt : e.val.1.val < e.val.2.val := e.2
        have h1 := e.val.1.isLt
        have h2 := e.val.2.isLt
        have hv : e.val.1.val = 0 ∧ e.val.2.val = 1 := by omega
        exact Subtype.ext
          (Prod.ext (Fin.ext hv.1) (Fin.ext hv.2))
      · rintro rfl
        exact hadj01
    have hnc0 : ¬ (graphOfEdges
        (∅ : Finset (OrderedEdge 2))).Connected := by
      intro hc
      have h01 := reachable_eq_of_no_adj graphOfEdges_empty_no_adj
        (hc.preconnected 0 1)
      exact absurd h01 (by decide)
    have hconn1 : (graphOfEdges
        ({⟨((0 : Fin 2), (1 : Fin 2)), by decide⟩} :
          Finset (OrderedEdge 2))).Connected :=
      connected_of_adj_fin2
        (Or.inl ⟨by decide, Finset.mem_singleton_self _⟩)
    unfold ursellCoeff graphUrsellCoeff connectedSpanningEdgeSets
    rw [hav, Finset.powerset_singleton, Finset.filter_insert,
      if_neg hnc0, Finset.filter_singleton, if_pos hconn1,
      Finset.sum_singleton]
    simp

/-! ## Separate cancellation tool (NOT used above) -/

/-- **7. The (1−1)^|S| cancellation lemma**, as an independent
    combinatorial tool for future inclusion–exclusion identities. It
    is deliberately NOT how the disconnected-graph capstone is proved
    (that one is structural: the filter is empty). -/
theorem sum_powerset_neg_one_pow_card {α : Type*} [DecidableEq α]
    (S : Finset α) :
    (∑ E ∈ S.powerset, (-1 : ℤ) ^ E.card)
      = if S = ∅ then 1 else 0 := by
  induction S using Finset.induction_on with
  | empty => simp
  | @insert a T ha ih =>
    have hdisj : Disjoint T.powerset
        (T.powerset.image (insert a)) := by
      rw [Finset.disjoint_left]
      intro E hE hE'
      obtain ⟨F, _, rfl⟩ := Finset.mem_image.mp hE'
      exact ha ((Finset.mem_powerset.mp hE)
        (Finset.mem_insert_self a F))
    have hinj : ∀ F₁ ∈ T.powerset, ∀ F₂ ∈ T.powerset,
        insert a F₁ = insert a F₂ → F₁ = F₂ := by
      intro F₁ h₁ F₂ h₂ heq
      have ha₁ : a ∉ F₁ := fun h => ha (Finset.mem_powerset.mp h₁ h)
      have ha₂ : a ∉ F₂ := fun h => ha (Finset.mem_powerset.mp h₂ h)
      have := congrArg (fun s => Finset.erase s a) heq
      simpa [Finset.erase_insert ha₁, Finset.erase_insert ha₂]
        using this
    have hcard : ∀ F ∈ T.powerset,
        (-1 : ℤ) ^ (insert a F).card = -(-1 : ℤ) ^ F.card := by
      intro F hF
      have haF : a ∉ F := fun h => ha (Finset.mem_powerset.mp hF h)
      rw [Finset.card_insert_of_not_mem haF, pow_succ]
      ring
    rw [Finset.powerset_insert, Finset.sum_union hdisj,
      Finset.sum_image hinj, Finset.sum_congr rfl hcard,
      Finset.sum_neg_distrib,
      if_neg (Finset.insert_ne_empty a T)]
    ring

end LatticeGauge
