/-
LatticeGauge/UrsellBounds.lean — Phase 3, thirty-ninth stone.

ELEMENTARY BOUNDS AND THE EXACT URSELL COEFFICIENT ON TREES
(architecture: Sol/GPT-5.6; execution: Fable). This stone CALIBRATES
the infrastructure; it does NOT produce a bound sufficient for
convergence, and says so explicitly:
|φ(G)| ≤ #(connected spanning edge sets) ≤ 2^{|E(G)|}, and in the
worst case over n vertices ≤ 2^{card(OrderedEdge n)} (the binomial
form 2^{C(n,2)} is registered as a future refinement) — an
exponential of order n², which no fixed smallness of the form c^n can
compensate uniformly in n. These are trivial combinatorial bounds,
obtained without any cancellation. The REAL content is the tree case:
a tree has EXACTLY ONE connected spanning edge subset (itself: every
edge of a tree is a bridge, and removing a bridge disconnects), hence
φ(T) = (−1)^{|E(T)|} and |φ(T)| = 1 — the structural base case that
the Penrose reduction will later exploit. The bridge to trees goes
through an abstract notion (EdgeEssentialForConnectivity) so the
finite combinatorics stays separated from the tree-specific API;
Mathlib's IsTree/IsBridge (isAcyclic_iff_forall_adj_isBridge,
isBridge_iff, deleteEdges_adj — signatures verified in the pinned
v4.15 source) supplies exactly the bridge property. n = 0 needs no
silent convention: a tree is connected, Connected requires Nonempty,
so IsTree already excludes n = 0. NOT HERE: Penrose identity, Penrose
trees, canonical trees, tree-graph inequality, Cayley, sums over n,
1/n!, log realZ, convergence, Kotecký–Preiss, polymer counting,
thermodynamic limits. NO axioms.
-/
import Mathlib
import LatticeGauge.Basic
import LatticeGauge.UrsellCoefficients
import LatticeGauge.UrsellSymmetry

open scoped Classical

namespace LatticeGauge

/-! ## 1-3. Elementary bounds (explicitly insufficient for
convergence) -/

/-- **1. Triangle bound**: |φ(G)| is at most the number of terms. -/
theorem graphUrsellCoeff_natAbs_le_card {n : ℕ}
    (G : SimpleGraph (Fin n)) :
    (graphUrsellCoeff G).natAbs
      ≤ (connectedSpanningEdgeSets G).card := by
  have habs : |graphUrsellCoeff G|
      ≤ ((connectedSpanningEdgeSets G).card : ℤ) := by
    unfold graphUrsellCoeff
    calc |∑ E ∈ connectedSpanningEdgeSets G, (-1 : ℤ) ^ E.card|
        ≤ ∑ E ∈ connectedSpanningEdgeSets G, |(-1 : ℤ) ^ E.card| :=
          Finset.abs_sum_le_sum_abs _ _
      _ = ∑ _E ∈ connectedSpanningEdgeSets G, (1 : ℤ) := by
          refine Finset.sum_congr rfl fun E _ => ?_
          rw [abs_pow, abs_neg, abs_one, one_pow]
      _ = ((connectedSpanningEdgeSets G).card : ℤ) := by
          rw [Finset.sum_const, nsmul_eq_mul, mul_one]
  rwa [Int.abs_eq_natAbs, Nat.cast_le] at habs

/-- **2a. The number of terms is at most the powerset count.** -/
theorem card_connectedSpanningEdgeSets_le {n : ℕ}
    (G : SimpleGraph (Fin n)) :
    (connectedSpanningEdgeSets G).card
      ≤ 2 ^ (availableEdges G).card := by
  calc (connectedSpanningEdgeSets G).card
      ≤ (availableEdges G).powerset.card :=
        Finset.card_le_card (Finset.filter_subset _ _)
    _ = 2 ^ (availableEdges G).card := Finset.card_powerset _

/-- **2b. CAPSTONE (trivial bound)**: |φ(G)| ≤ 2^{|E(G)|} — a purely
    combinatorial bound with no cancellations. Insufficient for any
    convergence statement. -/
theorem graphUrsellCoeff_natAbs_le_pow_edges {n : ℕ}
    (G : SimpleGraph (Fin n)) :
    (graphUrsellCoeff G).natAbs ≤ 2 ^ (availableEdges G).card :=
  le_trans (graphUrsellCoeff_natAbs_le_card G)
    (card_connectedSpanningEdgeSets_le G)

/-- **3. Universal vertex bound** via the full canonical-edge type
    (the `Nat.choose n 2` form is a registered future refinement;
    this bound grows like an exponential of order n² and CANNOT be
    compensated by any c^n smallness uniformly in n). -/
theorem graphUrsellCoeff_natAbs_le_pow_card {n : ℕ}
    (G : SimpleGraph (Fin n)) :
    (graphUrsellCoeff G).natAbs
      ≤ 2 ^ Fintype.card (OrderedEdge n) :=
  le_trans (graphUrsellCoeff_natAbs_le_pow_edges G)
    (Nat.pow_le_pow_right (by norm_num)
      (Finset.card_le_univ _))

/-! ## 4-5. Structural lemmas -/

/-- **4. The graph generated by ALL available edges is the graph
    itself.** -/
theorem graphOfEdges_availableEdges {n : ℕ}
    (G : SimpleGraph (Fin n)) :
    graphOfEdges (availableEdges G) = G := by
  ext i j
  constructor
  · intro h
    rcases h with ⟨_, hm⟩ | ⟨_, hm⟩
    · exact mem_availableEdges.mp hm
    · exact (mem_availableEdges.mp hm).symm
  · intro h
    rw [graphOfEdges_adj_iff_canonical h.ne, mem_availableEdges]
    exact (adj_canonicalOrderedEdge G h.ne).mpr h

theorem graphOfEdges_mono {n : ℕ}
    {E F : Finset (OrderedEdge n)} (h : E ⊆ F) :
    graphOfEdges E ≤ graphOfEdges F := by
  intro i j hij
  rcases hij with ⟨hlt, hm⟩ | ⟨hlt, hm⟩
  · exact Or.inl ⟨hlt, h hm⟩
  · exact Or.inr ⟨hlt, h hm⟩

/-- **5. An edge essential for connectivity**: available, and its
    removal disconnects the generated graph. Keeps the finite
    combinatorics independent of the tree-specific API. -/
def EdgeEssentialForConnectivity {n : ℕ} (G : SimpleGraph (Fin n))
    (e : OrderedEdge n) : Prop :=
  e ∈ availableEdges G ∧
    ¬ (graphOfEdges ((availableEdges G).erase e)).Connected

/-- **Abstract lemma**: if every available edge is essential, the only
    connected spanning edge set is the full one. -/
theorem eq_availableEdges_of_all_essential {n : ℕ}
    {G : SimpleGraph (Fin n)}
    (hall : ∀ e ∈ availableEdges G, EdgeEssentialForConnectivity G e)
    {E : Finset (OrderedEdge n)}
    (hE : E ∈ connectedSpanningEdgeSets G) :
    E = availableEdges G := by
  obtain ⟨hsub, hconn⟩ := mem_connectedSpanningEdgeSets.mp hE
  by_contra hne
  obtain ⟨e, heav, heE⟩ : ∃ e ∈ availableEdges G, e ∉ E := by
    by_contra hno
    push_neg at hno
    exact hne (Finset.Subset.antisymm hsub hno)
  have hsub' : E ⊆ (availableEdges G).erase e := fun x hx =>
    Finset.mem_erase.mpr ⟨fun hxe => heE (hxe ▸ hx), hsub hx⟩
  exact (hall e heav).2 (hconn.mono (graphOfEdges_mono hsub'))

/-! ## 6-8. Trees -/

/-- **6. In a tree, every available edge is essential**: every edge of
    a tree is a bridge (isAcyclic_iff_forall_adj_isBridge), and the
    graph generated without it embeds into the bridge-deleted graph. -/
theorem isTree_all_edges_essential {n : ℕ}
    {G : SimpleGraph (Fin n)} (hG : G.IsTree) :
    ∀ e ∈ availableEdges G, EdgeEssentialForConnectivity G e := by
  intro e heav
  refine ⟨heav, ?_⟩
  intro hconn
  have hadj : G.Adj e.val.1 e.val.2 := mem_availableEdges.mp heav
  have hbridge : G.IsBridge s(e.val.1, e.val.2) :=
    (SimpleGraph.isAcyclic_iff_forall_adj_isBridge.mp
      hG.IsAcyclic) hadj
  obtain ⟨-, hnoreach⟩ := SimpleGraph.isBridge_iff.mp hbridge
  apply hnoreach
  have hle : graphOfEdges ((availableEdges G).erase e)
      ≤ G.deleteEdges {s(e.val.1, e.val.2)} := by
    intro i j hij
    rw [SimpleGraph.deleteEdges_adj]
    rcases hij with ⟨hlt, hm⟩ | ⟨hlt, hm⟩
    · obtain ⟨hne_e, hmav⟩ := Finset.mem_erase.mp hm
      refine ⟨mem_availableEdges.mp hmav, ?_⟩
      rw [Set.mem_singleton_iff]
      intro hsym
      rcases Sym2.eq_iff.mp hsym with ⟨h1, h2⟩ | ⟨h1, h2⟩
      · exact hne_e (Subtype.ext (Prod.ext h1 h2))
      · have h := e.2
        rw [← h2, ← h1] at h
        exact absurd hlt (lt_asymm h)
    · obtain ⟨hne_e, hmav⟩ := Finset.mem_erase.mp hm
      refine ⟨(mem_availableEdges.mp hmav).symm, ?_⟩
      rw [Set.mem_singleton_iff]
      intro hsym
      rcases Sym2.eq_iff.mp hsym with ⟨h1, h2⟩ | ⟨h1, h2⟩
      · have h := e.2
        rw [← h1, ← h2] at h
        exact absurd hlt (lt_asymm h)
      · exact hne_e (Subtype.ext (Prod.ext h2 h1))
  exact (hconn.preconnected e.val.1 e.val.2).mono hle

/-- **7. STRUCTURAL CAPSTONE: a tree has exactly one connected
    spanning edge set — itself.** (IsTree already excludes n = 0:
    Connected requires Nonempty.) -/
theorem connectedSpanningEdgeSets_eq_of_isTree {n : ℕ}
    {G : SimpleGraph (Fin n)} (hG : G.IsTree) :
    connectedSpanningEdgeSets G = {availableEdges G} := by
  ext E
  rw [Finset.mem_singleton]
  constructor
  · intro hE
    exact eq_availableEdges_of_all_essential
      (isTree_all_edges_essential hG) hE
  · rintro rfl
    rw [mem_connectedSpanningEdgeSets]
    refine ⟨Finset.Subset.refl _, ?_⟩
    rw [graphOfEdges_availableEdges]
    exact hG.isConnected

/-- **8. EXACT COEFFICIENT ON TREES**: φ(T) = (−1)^{|E(T)|}. -/
theorem graphUrsellCoeff_of_isTree {n : ℕ}
    {G : SimpleGraph (Fin n)} (hG : G.IsTree) :
    graphUrsellCoeff G = (-1 : ℤ) ^ (availableEdges G).card := by
  unfold graphUrsellCoeff
  rw [connectedSpanningEdgeSets_eq_of_isTree hG,
    Finset.sum_singleton]

/-- **|φ(T)| = 1**: trees saturate nothing — they are the structural
    base case that the future Penrose reduction will count. -/
theorem graphUrsellCoeff_natAbs_of_isTree {n : ℕ}
    {G : SimpleGraph (Fin n)} (hG : G.IsTree) :
    (graphUrsellCoeff G).natAbs = 1 := by
  rw [graphUrsellCoeff_of_isTree hG, Int.natAbs_pow]
  simp

end LatticeGauge
